services:
    php:
        container_name: laravel_ghipy-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        depends_on:
            -   db
        networks:
            - laravel

    nginx:
        container_name: laravel_ghipy-nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    db:
        container_name: laravel_ghipy-db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "--user=laraveluser", "--password=secret", "--host=127.0.0.1", "ping", "--silent" ]
            interval: 2s
            timeout: 10s
            retries: 10

    wiremock:
        image: wiremock/wiremock:latest
        container_name: wiremock
        ports:
            - "9001:8080"
        volumes:
            - ./tests/Core/Gifs/Infrastructure/Wiremock:/home/wiremock/mappings
        environment:
            - WIREMOCK_ROOT_DIRECTORY=/home/wiremock
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
